# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release

      - name: Run tests
        run: dotnet test

      - name: Publish project
        run: dotnet publish -c Release -o ./publish

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
         name: aspnetcore-build
         path: ./publish 

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
         name: aspnetcore-build
         path: ./downloaded


name: Release Pipeline

on:
  workflow_dispatch:  # Manual trigger
  push:
    tags:
      - 'v*'          # Trigger on version tags like v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build in Release mode
        run: dotnet build --configuration Release

      - name: Publish to Release folder
        run: dotnet publish -c Release -o ./Release

      - name: Upload Release artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-artifacts
          path: ./Release         

   
